## Podmíněné formátování

In [31]:
import pandas as pd

In [ ]:
url_food_nutrient = "https://kodim.cz/cms/assets/czechitas/python-data-1/python-pro-data-1/podmineny-vyber/podmineny-vyber/food_nutrient.csv"
food_nutrient = pd.read_csv(url_food_nutrient)
food_nutrient.head()

,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,loq,footnote,min_year_acquired,name,unit_name
0,1106032,1257,NaN,NaN,71.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total trans",G
1,1107191,1257,NaN,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total trans",G
2,1107295,1257,NaN,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total trans",G
3,1107475,1257,NaN,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total trans",G
4,1107528,1257,0.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total trans",G

 Stručný popis sloupců tabulky.

- `id`: Identifikační číslo záznamu.
- `fdc_id`: Identifikační číslo potraviny, ke které se vztahuje živina.
- `nutrient_id`: Identifikační číslo živiny.
- `amount`: Množství živiny v potravině.
- `data_points`: Počet datových bodů použitých pro výpočet průměru.
- `derivation_id`: Identifikační číslo metody, kterou byla hodnota živiny odvozena.
- `standard_error`: Standardní chyba měření množství živiny.
- `min`: Minimální hodnota množství živiny nalezlá v potravině.
- `max`: Maximální hodnota množství živiny nalezlá v potravině.
- `median`: Medián hodnot množství živiny v potravině.
- `footnote`: Poznámka nebo dodatečné informace o živině.
- `name`: Název živiny.
- `unit_name`: Název jednotky, ve které se měří živina.
- `nutrient_nbr`: Unikátní číslo identifikující živinu nebo potravinovou složku​.

In [46]:
food_nutrient.info()

<class 'pandas.core.frame.DataFrame'>
Index: 135332 entries, 4 to 135335
Data columns (total 5 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   fdc_id       135332 non-null  int64
 1   nutrient_id  135332 non-null  int64
 2   amount       135332 non-null  float64
 3   name         135332 non-null  object
 4   unit_name    135332 non-null  object
dtypes: float64(1), int64(2), object(2)
memory usage: 6.2+ MB

In [48]:
print(food_nutrient.columns.tolist())

['fdc_id', 'nutrient_id', 'amount', 'name', 'unit_name']

In [33]:
food_nutrient.drop(columns=['data_points', 'min', 'max', 'median', 'loq', 'min_year_acquired', 'derivation_id', 'footnote'], inplace=True)
food_nutrient

         fdc_id  nutrient_id  amount                      name unit_name
0       1106032         1257     NaN  Fatty acids, total trans         G
1       1107191         1257     NaN  Fatty acids, total trans         G
2       1107295         1257     NaN  Fatty acids, total trans         G
3       1107475         1257     NaN  Fatty acids, total trans         G
4       1107528         1257     0.0  Fatty acids, total trans         G
...         ...          ...     ...                       ...       ...
135331  2614074         2068     0.0                 Vitamin E        MG
135332  2622536         2068     2.0                 Vitamin E        MG
135333  2622742         2068    13.0                 Vitamin E        MG
135334  2627542         2068     2.0                 Vitamin E        MG
135335  2654454         2068    25.0                 Vitamin E        MG

[135336 rows x 5 columns]

### Co vlastně umí série

In [34]:
food_nutrient["name"]

0         Fatty acids, total trans
1         Fatty acids, total trans
2         Fatty acids, total trans
3         Fatty acids, total trans
4         Fatty acids, total trans
                    ...
135331                   Vitamin E
135332                   Vitamin E
135333                   Vitamin E
135334                   Vitamin E
135335                   Vitamin E
Name: name, Length: 135336, dtype: object

In [35]:
food_nutrient["name"].unique()
# food_nutrient["name"].nunique()

array(['Fatty acids, total trans', 'Fatty acids, total polyunsaturated',
       'Cholesterol', 'Potassium, K', 'Energy', 'Iron, Fe',
       'Vitamin C, total ascorbic acid', 'Fatty acids, total saturated',
       'Calcium, Ca', 'Fatty acids, total monounsaturated', 'Sodium, Na',
       'Vitamin A, IU', 'Sugars, total including NLEA',
       'Fiber, total dietary', 'Vitamin D (D2 + D3), International Units',
       'Carbohydrate, by difference', 'Total lipid (fat)', 'Protein',
       'Folic acid', 'Folate, DFE', 'Riboflavin', 'Thiamin',
       'Vitamin B-12', 'Vitamin B-6', 'Phosphorus, P', 'Manganese, Mn',
       'Magnesium, Mg', 'Niacin', 'Sugars, added', 'Folate, total',
       'Selenium, Se', 'Pantothenic acid', 'Iodine, I', 'Zinc, Zn',
       'Vitamin E', 'Fiber, soluble', 'Fiber, insoluble',
       'Total sugar alcohols', 'Vitamin K (phylloquinone)', 'Copper, Cu',
       'Carbohydrate, other', 'Molybdenum, Mo', 'Chromium, Cr', 'Biotin',
       'Inulin', 'Vitamin E (alpha-tocopherol)', 'Xylitol',
       'Choline, total', 'Chlorine, Cl', 'Lactose',
       'Vitamin D3 (cholecalciferol)', 'Water', 'Ash', 'Vitamin A, RAE',
       'Retinol', 'MUFA 18:1', 'SFA 16:0', 'PUFA 18:3', 'PUFA 18:2',
       'Carotene, alpha', 'Starch', 'Tocotrienol, alpha', 'MUFA 15:1',
       'Tryptophan', 'Carotene, beta', 'PUFA 22:5 n-3 (DPA)', 'SFA 18:0',
       'Tocotrienol, beta', 'MUFA 22:1', 'SFA 22:0', 'PUFA 18:4',
       'Tocotrienol, delta', 'Maltose', 'Tocopherol, delta', 'Methionine',
       'PUFA 20:3', 'Glutamic acid', 'PUFA 18:3 n-6 c,c,c', 'Fructose',
       'Glucose', 'Tocopherol, beta', 'Vitamin E, added', 'Sucrose',
       'Aspartic acid', 'Phenylalanine', 'Cystine', 'Glycine',
       'Galactose', 'Theobromine', 'SFA 4:0', 'Valine', 'MUFA 14:1',
       'Threonine', 'PUFA 22:6 n-3 (DHA)', 'SFA 14:0', 'Alcohol, ethyl',
       'PUFA 20:2 n-6 c,c', 'Tocopherol, gamma', 'SFA 6:0', 'SFA 8:0',
       'SFA 10:0', 'Histidine', 'Lycopene', 'Arginine', 'Folate, food',
       'SFA 20:0', 'Vitamin K (Dihydrophylloquinone)', 'MUFA 17:1',
       'Lysine', 'SFA 17:0', 'Tocotrienol, gamma', 'Serine', 'Caffeine',
       'Proline', 'MUFA 20:1', 'Tyrosine', 'Cryptoxanthin, beta',
       'SFA 12:0', 'Isoleucine', 'SFA 15:0', 'MUFA 16:1',
       'Lutein + zeaxanthin', 'Leucine', 'Vitamin B-12, added', 'Alanine',
       'PUFA 20:5 n-3 (EPA)', 'PUFA 20:4', 'Vitamin D (D2 + D3)',
       'Betaine', 'Vitamin K (Menaquinone-4)', 'MUFA 16:1 c', 'PUFA 21:5',
       'MUFA 24:1 c', 'SFA 24:0', 'PUFA 22:4', 'Hydroxyproline',
       'PUFA 18:3 n-3 c,c,c (ALA)', 'TFA 18:2 t,t',
       'Fatty acids, total trans-polyenoic',
       'Fatty acids, total trans-monoenoic', 'TFA 18:1 t',
       'PUFA 18:2 n-6 c,c', 'PUFA 18:2 CLAs', 'MUFA 22:1 c',
       'TFA 18:2 t not further defined', 'PUFA 20:3 n-3', 'TFA 22:1 t',
       'MUFA 18:1 c', 'PUFA 20:3 n-6', 'TFA 16:1 t', 'Fluoride, F',
       'PUFA 18:3i', 'Stigmasterol', 'Beta-sitosterol', 'Campesterol',
       'PUFA 18:2 i', 'SFA 13:0', 'Phytosterols',
       'Vitamin D2 (ergocalciferol)', 'Nitrogen', 'SFA 11:0',
       'PUFA 20:3 n-9', 'MUFA 20:1 c', 'PUFA 22:2', 'MUFA 22:1 n-9',
       'TFA 18:3 t', 'MUFA 14:1 c', '25-hydroxycholecalciferol',
       'SFA 21:0', 'SFA 9:0', 'SFA 7:0', 'MUFA 22:1 n-11', 'PUFA 22:3',
       'SFA 23:0', 'TFA 14:1 t', 'TFA 20:1 t', 'MUFA 12:1', 'SFA 5:0',
       'Cysteine', 'Zeaxanthin', 'trans-beta-Carotene', 'trans-Lycopene',
       'Lutein', 'cis-beta-Carotene', 'cis-Lycopene',
       'Cryptoxanthin, alpha', 'cis-Lutein/Zeaxanthin',
       'Total fat (NLEA)', 'Sugars, Total', 'Sulfur, S', 'Cobalt, Co',
       'Boron, B', 'Nickel, Ni', 'Vitamin E (label entry primarily)',
       'Epigallocatechin-3-gallate', 'Beta-sitostanol',
       'Delta-5-avenasterol', 'Stigmastadiene', 'Delta-7-Stigmastenol',
       'Beta-glucan', 'Ergosterol', ' Ergosta-5,7-dienol', 'Oxalic acid',
       'High Molecular Weight Dietary Fiber (HMWDF)', 'Vitamin A'],
      dtype=object)

In [ ]:
food_nutrient["name"].value_counts().head(10)  #head určuje kolik hodnot chci zobrazit

name
Protein                         9553
Sodium, Na                      9499
Energy                          9473
Total lipid (fat)               9413
Carbohydrate, by difference     9357
Sugars, total including NLEA    8995
Fatty acids, total saturated    8250
Cholesterol                     8071
Fiber, total dietary            8011
Fatty acids, total trans        8000
Name: count, dtype: int64

In [ ]:
#chci vyfiltrovat potraviny, kde je hořčík:
food_nutrient["name"] == "Magnesium, Mg"  #dvojité rovná se - používám, když píšu textové hodnoty  
#False  mi říká, pro každý řádek, že podmínka není splněna.   #když říkám "vyber" píšu [] - hranaté závorky

4         False
5         False
6         False
7         False
8         False
          ...
135331    False
135332    False
135333    False
135334    False
135335    False
Name: name, Length: 135332, dtype: bool

In [53]:
food_nutrient[food_nutrient["name"] == "Magnesium, Mg"]  ##když říkám "vyber" píšu [] - hranaté závorky
# dataframe[sloupec == hodnota]
# další způsob: podmínka
# is-magnesium = food_nutrient["name"] == "Magnesium, Mg"

         fdc_id  nutrient_id  amount           name unit_name
125766  1108349         1090   147.0  Magnesium, Mg        MG
125767  1109796         1090   156.0  Magnesium, Mg        MG
125768  1114461         1090   107.0  Magnesium, Mg        MG
125769  1114961         1090   267.0  Magnesium, Mg        MG
125770  1118500         1090   158.0  Magnesium, Mg        MG
...         ...          ...     ...            ...       ...
126155  2645435         1090    28.9  Magnesium, Mg        MG
126156  2653037         1090     4.0  Magnesium, Mg        MG
126157  2654454         1090   257.0  Magnesium, Mg        MG
126158  2658921         1090     8.0  Magnesium, Mg        MG
126159  2661782         1090    50.0  Magnesium, Mg        MG

[394 rows x 5 columns]

In [54]:
magnesium.describe()

             fdc_id  nutrient_id       amount
count  3.940000e+02        394.0   394.000000
mean   1.494746e+06       1090.0   102.079797
std    8.224790e+05          0.0   210.755384
min    1.675510e+05       1090.0     0.000000
25%    6.561875e+05       1090.0    13.000000
50%    1.674326e+06       1090.0    43.000000
75%    2.265302e+06       1090.0   124.250000
max    2.661782e+06       1090.0  2941.000000

In [55]:
magnesium["amount"].describe()

count     394.000000
mean      102.079797
std       210.755384
min         0.000000
25%        13.000000
50%        43.000000
75%       124.250000
max      2941.000000
Name: amount, dtype: float64

### Podmíněný výběr

Uvažujme, že nám jde o obsah hořčíku (Magnesium), protože naším úkolem je doporučit potraviny lidem s nedostatkem hořčíku.

Při použití operátorů pro porovnávání vždy získáme hodnotu typu `bool`.

In [37]:
food_nutrient["name"] == "Magnesium, Mg"

0         False
1         False
2         False
3         False
4         False
          ...
135331    False
135332    False
135333    False
135334    False
135335    False
Name: name, Length: 135336, dtype: bool

`pandas` teď jednoduše udělají to, že vypíšou ty řádky řádky, kde má náš polotovar hodnotu `True` a ty, které mají hodnotu `False`, před námi skryjí.

In [38]:
magnesium = food_nutrient[food_nutrient["name"] == "Magnesium, Mg"]
magnesium.head()

         fdc_id  nutrient_id  amount           name unit_name
125766  1108349         1090   147.0  Magnesium, Mg        MG
125767  1109796         1090   156.0  Magnesium, Mg        MG
125768  1114461         1090   107.0  Magnesium, Mg        MG
125769  1114961         1090   267.0  Magnesium, Mg        MG
125770  1118500         1090   158.0  Magnesium, Mg        MG

### Popisná statistika

In [39]:
magnesium["amount"].describe()

count     394.000000
mean      102.079797
std       210.755384
min         0.000000
25%        13.000000
50%        43.000000
75%       124.250000
max      2941.000000
Name: amount, dtype: float64

Naším úkolem je vybrat potraviny, které mají vyšší množství hořčíku. K tomu opět využijeme dotaz. 

Uvažujeme, že nás zajímají potraviny, které mají více než 100 gramů hořčíku.

In [56]:
magnesium["amount"]

125766    147.0
125767    156.0
125768    107.0
125769    267.0
125770    158.0
          ...
126155     28.9
126156      4.0
126157    257.0
126158      8.0
126159     50.0
Name: amount, Length: 394, dtype: float64

In [57]:
magnesium[magnesium["amount"] > 100]

         fdc_id  nutrient_id  amount           name unit_name
125766  1108349         1090   147.0  Magnesium, Mg        MG
125767  1109796         1090   156.0  Magnesium, Mg        MG
125768  1114461         1090   107.0  Magnesium, Mg        MG
125769  1114961         1090   267.0  Magnesium, Mg        MG
125770  1118500         1090   158.0  Magnesium, Mg        MG
...         ...          ...     ...            ...       ...
126141  2550641         1090   218.0  Magnesium, Mg        MG
126147  2558685         1090   133.0  Magnesium, Mg        MG
126148  2592707         1090   207.0  Magnesium, Mg        MG
126154  2627542         1090   118.0  Magnesium, Mg        MG
126157  2654454         1090   257.0  Magnesium, Mg        MG

[117 rows x 5 columns]

## Operatory pro podminky
```
>
<
==
!=
```

## Operatory pro podminky

```python
print("ahoj")
>
<
==
!=
```

In [71]:
is_magnesium = food_nutrient["name"] == "Magnesium, Mg"
is_over_limit = food_nutrient["amount"] > 100
# dataframe[(podminka 1) & | (podminka 2)]  .. je to v komentáři, aby to nerozbíjelo kóde
food_nutrient[(is_magnesium)
              & (is_over_limit)
]

         fdc_id  nutrient_id  amount           name unit_name
125766  1108349         1090   147.0  Magnesium, Mg        MG
125767  1109796         1090   156.0  Magnesium, Mg        MG
125768  1114461         1090   107.0  Magnesium, Mg        MG
125769  1114961         1090   267.0  Magnesium, Mg        MG
125770  1118500         1090   158.0  Magnesium, Mg        MG
...         ...          ...     ...            ...       ...
126141  2550641         1090   218.0  Magnesium, Mg        MG
126147  2558685         1090   133.0  Magnesium, Mg        MG
126148  2592707         1090   207.0  Magnesium, Mg        MG
126154  2627542         1090   118.0  Magnesium, Mg        MG
126157  2654454         1090   257.0  Magnesium, Mg        MG

[117 rows x 5 columns]

In [ ]:
#nebo: 
food_nutrient[(food_nutrient["name"] == "Magnesium, Mg")
              & (food_nutrient["amount"] > 100)
]

#když mám víc podmínek, musím se rozhodnout, kterou chci preferovat, nebo chci obě, nebo má být splněna alespoň jedna

         fdc_id  nutrient_id  amount           name unit_name
125766  1108349         1090   147.0  Magnesium, Mg        MG
125767  1109796         1090   156.0  Magnesium, Mg        MG
125768  1114461         1090   107.0  Magnesium, Mg        MG
125769  1114961         1090   267.0  Magnesium, Mg        MG
125770  1118500         1090   158.0  Magnesium, Mg        MG
...         ...          ...     ...            ...       ...
126141  2550641         1090   218.0  Magnesium, Mg        MG
126147  2558685         1090   133.0  Magnesium, Mg        MG
126148  2592707         1090   207.0  Magnesium, Mg        MG
126154  2627542         1090   118.0  Magnesium, Mg        MG
126157  2654454         1090   257.0  Magnesium, Mg        MG

[117 rows x 5 columns]

In [64]:
magnesium_limit = magnesium[magnesium["amount"] > 100]
magnesium_limit

         fdc_id  nutrient_id  amount           name unit_name
125766  1108349         1090   147.0  Magnesium, Mg        MG
125767  1109796         1090   156.0  Magnesium, Mg        MG
125768  1114461         1090   107.0  Magnesium, Mg        MG
125769  1114961         1090   267.0  Magnesium, Mg        MG
125770  1118500         1090   158.0  Magnesium, Mg        MG
...         ...          ...     ...            ...       ...
126141  2550641         1090   218.0  Magnesium, Mg        MG
126147  2558685         1090   133.0  Magnesium, Mg        MG
126148  2592707         1090   207.0  Magnesium, Mg        MG
126154  2627542         1090   118.0  Magnesium, Mg        MG
126157  2654454         1090   257.0  Magnesium, Mg        MG

[117 rows x 5 columns]

### Spojení více podmínek

Pokud chceme, aby musely být splněny obě podmínky, vložíme mezi ně symbol `&`. 

Pokud chceme, aby stačilo splnění jedné podmínky, použijeme symbol `|`.

Naším úkolem bude vybrat potraviny, které mají mezi 30 a 500 mg vápníku.

In [ ]:
calcium = food_nutrient[food_nutrient["name"] == "Calcium, Ca"]
calcium_limit = calcium[(calcium["amount"] > 30) & (calcium["amount"] < 500)]
calcium_limit

        fdc_id  nutrient_id  amount         name unit_name
51848  1107475         1087   129.0  Calcium, Ca        MG
51849  1107528         1087   107.0  Calcium, Ca        MG
51850  1108007         1087    31.0  Calcium, Ca        MG
51852  1108349         1087   382.0  Calcium, Ca        MG
51853  1108803         1087    33.0  Calcium, Ca        MG
...        ...          ...     ...          ...       ...
59729  2659382         1087    67.0  Calcium, Ca        MG
59730  2659508         1087    31.0  Calcium, Ca        MG
59733  2660573         1087    80.0  Calcium, Ca        MG
59734  2660613         1087   133.0  Calcium, Ca        MG
59741  2661782         1087    83.0  Calcium, Ca        MG

[4005 rows x 5 columns]

In [66]:
calcium_limit = food_nutrient[
    (food_nutrient["name"] == "Calcium, Ca")
    & (food_nutrient["amount"] > 30)
    & (food_nutrient["amount"] < 500)
]

calcium_limit

        fdc_id  nutrient_id  amount         name unit_name
51848  1107475         1087   129.0  Calcium, Ca        MG
51849  1107528         1087   107.0  Calcium, Ca        MG
51850  1108007         1087    31.0  Calcium, Ca        MG
51852  1108349         1087   382.0  Calcium, Ca        MG
51853  1108803         1087    33.0  Calcium, Ca        MG
...        ...          ...     ...          ...       ...
59729  2659382         1087    67.0  Calcium, Ca        MG
59730  2659508         1087    31.0  Calcium, Ca        MG
59733  2660573         1087    80.0  Calcium, Ca        MG
59734  2660613         1087   133.0  Calcium, Ca        MG
59741  2661782         1087    83.0  Calcium, Ca        MG

[4005 rows x 5 columns]

In [ ]:
calcium.describe()  #kontrola

             fdc_id  nutrient_id        amount
count  7.899000e+03       7899.0   7899.000000
mean   1.594891e+06       1087.0    113.772152
std    6.817332e+05          0.0    803.420773
min    1.675510e+05       1087.0      0.000000
25%    1.130902e+06       1087.0      0.000000
50%    1.677877e+06       1087.0     36.000000
75%    2.148011e+06       1087.0    107.000000
max    2.662182e+06       1087.0  56818.000000

Pokud chceme, aby stačilo splnění jedné podmínky, použijeme symbol `|`.

In [ ]:
%%time
%time %time calcium_limit = food_nutrient[(food_nutrient["name"] == "Calcium, Ca") & (food_nutrient["amount"] > 30) & (food_nutrient["amount"] < 500)] # tady je to napsané v Pandas

%time calcium_limit = food_nutrient.query('name == "Calcium, Ca" and 30 < amount < 500')    #tady se kód podobá SQLite

%time calcium_limit = food_nutrient[(food_nutrient["name"] == "Calcium, Ca") & food_nutrient["amount"].between(30, 500, inclusive="neither")]   #.between - zadávám od-do, inclusive="neither"

%time calcium_limit = food_nutrient.loc[(food_nutrient["name"] == "Calcium, Ca") & (food_nutrient["amount"] > 30) & (food_nutrient["amount"] < 500)]    #.loc 

#který kód si vybrat? pokud nemám nárok na ... můžu si vybrat, který chci. Pokud mám obří data, pak už ten způsob hraje roli (kód může běžet hodinu, nebo 10 minut).

CPU times: user 19 ms, sys: 3.15 ms, total: 22.2 ms
Wall time: 36.7 ms
CPU times: user 21 ms, sys: 3.53 ms, total: 24.5 ms
Wall time: 42.3 ms
CPU times: user 16.8 ms, sys: 4.77 ms, total: 21.6 ms
Wall time: 40.3 ms
CPU times: user 16 ms, sys: 481 μs, total: 16.5 ms
Wall time: 18 ms
CPU times: user 17.1 ms, sys: 657 μs, total: 17.8 ms
Wall time: 30.2 ms
CPU times: user 75.8 ms, sys: 9.77 ms, total: 85.6 ms
Wall time: 138 ms

### Práce s chybějícími hodnotami

**`isna()`, `notna()`**

Obě metody vrací hodnoty `True` nebo `False`

In [77]:
food_nutrient[food_nutrient["amount"].isna()]   #chybějící hodnota: Kde je.

Empty DataFrame
Columns: [fdc_id, nutrient_id, amount, name, unit_name]
Index: []

In [78]:
food_nutrient[food_nutrient["amount"].isnull()] #chybějící hodnota: Kde není

Empty DataFrame
Columns: [fdc_id, nutrient_id, amount, name, unit_name]
Index: []

In [79]:
food_nutrient[food_nutrient["amount"].notna()]

         fdc_id  nutrient_id  amount                      name unit_name
4       1107528         1257     0.0  Fatty acids, total trans         G
5       1108007         1257     0.0  Fatty acids, total trans         G
6       1108158         1257     0.0  Fatty acids, total trans         G
7       1108349         1257     0.0  Fatty acids, total trans         G
8       1108803         1257     0.0  Fatty acids, total trans         G
...         ...          ...     ...                       ...       ...
135331  2614074         2068     0.0                 Vitamin E        MG
135332  2622536         2068     2.0                 Vitamin E        MG
135333  2622742         2068    13.0                 Vitamin E        MG
135334  2627542         2068     2.0                 Vitamin E        MG
135335  2654454         2068    25.0                 Vitamin E        MG

[135332 rows x 5 columns]

**Jak chybějící hodnoty odstranit**

In [69]:
food_nutrient = food_nutrient.dropna(subset="amount")
food_nutrient.head(3)

    fdc_id  nutrient_id  amount                      name unit_name
4  1107528         1257     0.0  Fatty acids, total trans         G
5  1108007         1257     0.0  Fatty acids, total trans         G
6  1108158         1257     0.0  Fatty acids, total trans         G

# Nahradit

In [80]:
food_nutrient.fillna("Boruvkovy kolac")

         fdc_id  nutrient_id  amount                      name unit_name
4       1107528         1257     0.0  Fatty acids, total trans         G
5       1108007         1257     0.0  Fatty acids, total trans         G
6       1108158         1257     0.0  Fatty acids, total trans         G
7       1108349         1257     0.0  Fatty acids, total trans         G
8       1108803         1257     0.0  Fatty acids, total trans         G
...         ...          ...     ...                       ...       ...
135331  2614074         2068     0.0                 Vitamin E        MG
135332  2622536         2068     2.0                 Vitamin E        MG
135333  2622742         2068    13.0                 Vitamin E        MG
135334  2627542         2068     2.0                 Vitamin E        MG
135335  2654454         2068    25.0                 Vitamin E        MG

[135332 rows x 5 columns]

In [82]:
url_food_nutrient = "https://kodim.cz/cms/assets/czechitas/python-data-1/python-pro-data-1/podmineny-vyber/podmineny-vyber/food_nutrient.csv"
food_nutrient = pd.read_csv(url_food_nutrient)
food_nutrient.fillna("Boruvkovy kolac")

,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,loq,footnote,min_year_acquired,name,unit_name
0,1106032,1257,Boruvkovy kolac,Boruvkovy kolac,71.0,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,"Fatty acids, total trans",G
1,1107191,1257,Boruvkovy kolac,Boruvkovy kolac,70.0,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,"Fatty acids, total trans",G
2,1107295,1257,Boruvkovy kolac,Boruvkovy kolac,70.0,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,"Fatty acids, total trans",G
3,1107475,1257,Boruvkovy kolac,Boruvkovy kolac,70.0,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,"Fatty acids, total trans",G
4,1107528,1257,0.0,Boruvkovy kolac,70.0,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,"Fatty acids, total trans",G
...,...,...,...,...,...,...,...,...,...,...,...,...,...
135331,2614074,2068,0.0,Boruvkovy kolac,71.0,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Vitamin E,MG
135332,2622536,2068,2.0,Boruvkovy kolac,70.0,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Vitamin E,MG
135333,2622742,2068,13.0,Boruvkovy kolac,70.0,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Vitamin E,MG
135334,2627542,2068,2.0,Boruvkovy kolac,75.0,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Vitamin E,MG
135335,2654454,2068,25.0,Boruvkovy kolac,70.0,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Boruvkovy kolac,Vitamin E,MG

In [84]:
food_nutrient["amount"] = food_nutrient["amount"].fillna("Boruvkovy kolac")