In [5]:
import pandas as pd

url_food_nutrient = "https://kodim.cz/cms/assets/czechitas/python-data-1/python-pro-data-1/podmineny-vyber/podmineny-vyber/food_nutrient.csv"
food_nutrient = pd.read_csv(url_food_nutrient)

In [18]:
food_nutrient.head()

,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,loq,footnote,min_year_acquired,name,unit_name
0,1106032,1257,NaN,NaN,71.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total trans",G
1,1107191,1257,NaN,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total trans",G
2,1107295,1257,NaN,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total trans",G
3,1107475,1257,NaN,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total trans",G
4,1107528,1257,0.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total trans",G

# Vláknina

In [6]:
food_nutrient[
    (food_nutrient["name"] == "Fiber, total dietary")
      & (food_nutrient["amount"] >= 10)
      ]

,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,loq,footnote,min_year_acquired,name,unit_name
83639,1109336,1079,10.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
83666,1114461,1079,10.7,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
83667,1114961,1079,10.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
83675,1117734,1079,10.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
83681,1118500,1079,11.1,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
...,...,...,...,...,...,...,...,...,...,...,...,...,...
91545,2638057,1079,15.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
91584,2651678,1079,39.5,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
91598,2654454,1079,10.7,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
91599,2654695,1079,11.8,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
91629,2660613,1079,10.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G

## Hlášení chyb

In [19]:
errors = food_nutrient[(food_nutrient["unit_name"] == "MG") & (food_nutrient["amount"] > 100000)]
errors

,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,loq,footnote,min_year_acquired,name,unit_name
18231,1048385,1092,101770.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Potassium, K",MG
18888,1527945,1092,176991.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Potassium, K",MG
63254,944746,1093,282828.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Sodium, Na",MG
65700,1599725,1093,323944.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Sodium, Na",MG
67418,1982925,1093,203125.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Sodium, Na",MG
68232,2149015,1093,415625.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Sodium, Na",MG
69486,2465074,1093,528986.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Sodium, Na",MG
69528,2472749,1093,857143.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Sodium, Na",MG
69647,2495397,1093,183333.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Sodium, Na",MG

In [ ]:
food_nutrient.to_csv("food_nutrient.csv")
# errors.to_csv("errors_reports.csv", index=False)

## Česká jména

In [23]:
url = "https://kodim.cz/cms/assets/czechitas/python-data-1/python-pro-data-1/podmineny-vyber/podmineny-vyber/ceska-jmena/jmena.csv"
jmena = pd.read_csv(url)

In [21]:
jmena.head()

,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,loq,footnote,min_year_acquired,name,unit_name
0,1106032,1257,NaN,NaN,71.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total trans",G
1,1107191,1257,NaN,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total trans",G
2,1107295,1257,NaN,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total trans",G
3,1107475,1257,NaN,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total trans",G
4,1107528,1257,0.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total trans",G

In [24]:
jmena[jmena["prumerny_vek"] > 60]

        jmeno  cetnost  prumerny_vek pohlavi      puvod
4       Marie   260526            65       ž  hebrejský
23       Věra   107388            63       ž  slovanský
30  Jaroslava    84556            63       ž  slovanský
38    Ludmila    72750            65       ž  slovanský
40     Zdeňka    69060            61       ž  slovanský
50    Jarmila    59666            65       ž  slovanský
53     Jiřina    55366            64       ž      řecký
64     Vlasta    41736            68       ž  slovanský
68     Božena    39851            72       ž  slovanský
70     Libuše    39269            66       ž  slovanský
71      Marta    38897            63       ž  aramejský
91     Růžena    28952            69       ž  slovanský
99     Zdenka    25416            68       ž  slovanský

In [25]:
jmena[jmena["prumerny_vek"] > 70]

     jmeno  cetnost  prumerny_vek pohlavi      puvod
68  Božena    39851            72       ž  slovanský

In [15]:
print(jmena.columns.tolist())

['fdc_id', 'nutrient_id', 'amount', 'data_points', 'derivation_id', 'min', 'max', 'median', 'loq', 'footnote', 'min_year_acquired', 'name', 'unit_name']

In [27]:
jmena[(jmena["cetnost"] >= 80000) & (jmena["cetnost"] <= 100000)]

        jmeno  cetnost  prumerny_vek pohlavi      puvod
29   Veronika    88854            25       ž      řecký
30  Jaroslava    84556            63       ž  slovanský
31   Vladimír    83762            56       m  slovanský
32     Tereza    83692            18       ž      řecký
33    Martina    81312            36       ž   latinský

In [28]:
jmena[(jmena["puvod"] == "slovanský") | (jmena["puvod"] == "hebrejský")]
# jmena[jmena["puvod"].isin(["slovanský", "hebrejský"])]

        jmeno  cetnost  prumerny_vek pohlavi      puvod
1         Jan   293938            40       m  hebrejský
3        Jana   264944            50       ž  hebrejský
4       Marie   260526            65       ž  hebrejský
5       Josef   211317            57       m  hebrejský
9    Jaroslav   172785            55       m  slovanský
10        Eva   152463            53       ž  hebrejský
11   Miroslav   147753            52       m  slovanský
12       Hana   145901            51       ž  hebrejský
13       Anna   134819            51       ž  hebrejský
14     Zdeněk   126094            54       m  slovanský
15     Václav   123927            51       m  slovanský
16     Michal   123324            32       m  hebrejský
21      Jakub   108013            19       m  hebrejský
22      Milan   107458            51       m  slovanský
23       Věra   107388            63       ž  slovanský
24      Alena   105093            55       ž  hebrejský
28      David   101311            25       m  hebrejský
30  Jaroslava    84556            63       ž  slovanský
31   Vladimír    83762            56       m  slovanský
34   Michaela    78823            28       ž  hebrejský
35      Jitka    78187            51       ž  hebrejský
38    Ludmila    72750            65       ž  slovanský
39   Ladislav    69797            55       m  slovanský
40     Zdeňka    69060            61       ž  slovanský
41      Ivana    68917            49       ž  slovanský
45  Stanislav    61889            54       m  slovanský
46     Eliška    61517            24       ž  hebrejský
47     Zuzana    61382            34       ž  hebrejský
48     Daniel    60935            23       m  hebrejský
50    Jarmila    59666            65       ž  slovanský
51      Radek    58589            36       m  slovanský
56    Vojtěch    52802            22       m  slovanský
58       Dana    50781            51       ž  hebrejský
61       Adam    47837            14       m  hebrejský
64     Vlasta    41736            68       ž  slovanský
66  Miroslava    41151            54       ž  slovanský
68     Božena    39851            72       ž  slovanský
70     Libuše    39269            66       ž  slovanský
72      Matěj    38519            13       m  hebrejský
73      Šárka    38339            37       ž  slovanský
82   Miloslav    32769            60       m  slovanský
84   Gabriela    31175            33       ž  hebrejský
85    Jaromír    30984            55       m  slovanský
89      Aneta    29840            17       ž  hebrejský
90     Simona    29618            30       ž  hebrejský
91     Růžena    28952            69       ž  slovanský
92      Radka    26939            38       ž  slovanský
93    Daniela    26536            38       ž  hebrejský
96  Vlastimil    26014            54       m  slovanský
97        Iva    26003            46       ž  slovanský
98      Miloš    25509            53       m  slovanský
99     Zdenka    25416            68       ž  slovanský

In [30]:
jmena["puvod"].value_counts(normalize=True) * 100  # v procentech

puvod
slovanský        29.0
hebrejský        23.0
řecký            20.0
latinský         17.0
německý           3.0
skandinávský      2.0
aramejský         2.0
neznámý           1.0
italský           1.0
straroněmecký     1.0
germánský         1.0
Name: proportion, dtype: float64